apiVersion : apps/v1
kind: Deployment
metadata:
  name: pythontest 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythontest
  template:
    metadata:
      labels:
        app: pythontest 
    spec:
      containers:
        - name: pythontest 
          image: akstestingdapr.azurecr.io/pythontest
          ports:
          - containerPort: 80